use 3to5;
select * from dummytcl;
start transaction;
insert into dummytcl values(3),(4);
savepoint S1;
update dummytcl set id= 5 where id=4;
savepoint S2;
delete from dummytcl where id= 5;
rollback to S2;
rollback to S1;
rollback;
-- day9
use excelr;
create table emp_tcl(emp_id int primary key, name varchar(20), age int );
select * from emp_tcl;
start transaction;
insert into emp_tcl values (1, 'may', 30);
savepoint s1;
update emp_tcl set name='May' where emp_id=1; 
savepoint S2;
delete from emp_tcl where emp; 
rollback to S2;
set sql_safe_updates =0;
rollback to s1;
rollback;
drop table emp_tcl;

create table emp_TCL (EMP_ID int, NAME varchar(30),AGE int);

start transaction;
insert into emp_tcl values(1,"Prerna",20),(2,"Shreya",29);
select * from emp_tcl;
savepoint s1;
update emp_tcl set name= "asmita" where emp_id= 2;
savepoint s2;
delete from emp_tcl where emp_id= 2;
savepoint s3;
rollback to s3;
rollback to s2;
rollback to s1;
rollback;
alter table emp_tcl drop age, add que int;
select length(name) from emp_tcl;
use 3to5;
create view v1 as select * from myemp order by salary desc limit 10;
select * from v1;
alter table v1 modify column first_name ='lexy' where emp_id=102;
select * from global;
select * from global where rowid= 40470;
create index new_index on global(rowid);
show index from global;
